[package]
name = "ethereum-provider-simple-example"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.12", features = ["csr"] }
log = "0.4.21"
leptos-ethereum-provider = { path = "../.." }
console_log = "1.0.0"
